# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-19 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date_to',
            field=models.DateField(),
        ),
    ]
